SET(EXECUTABLE_OUTPUT_PATH "${PROJ_BIN_DIR}")
SET(LIBRARY_OUTPUT_PATH "${PROJ_LIB_DIR}")

if(NOT EXISTS "${PROJ_OUTPUT_DIR}/conf/")
    file(GLOB PROJ_CONFIG_FINE "${PROJ_ROOT_DIR}/conf/*")
    file(COPY ${PROJ_CONFIG_FINE} DESTINATION "${PROJ_OUTPUT_DIR}/conf/")
else()
    message("Config has already exits")
endif ()

macro(add_add_subdirs)
    file(GLOB dirs "*")
    foreach (dir IN LISTS dirs)
        if(IS_DIRECTORY ${dir} AND EXISTS ${dir}/CMakeLists.txt)
            add_subdirectory("${dir}")
        endif ()
    endforeach ()
endmacro()

function(build_shared_library LIB_NAME)
    set(${LIB_NAME}_DIR ${CMAKE_CURRENT_SOURCE_DIR})
    file(GLOB ${LIB_NAME}_header "${${LIB_NAME}_DIR}/*.h" "${${LIB_NAME}_DIR}/*.hpp")
    file(GLOB ${LIB_NAME}_src "${${LIB_NAME}_DIR}/*.c" "${${LIB_NAME}_DIR}/*.cpp")
    add_library(${LIB_NAME} SHARED ${${LIB_NAME}_src} ${${LIB_NAME}_header})
    target_link_libraries(${LIB_NAME} PRIVATE ${SYSTEM_LIBS} ${ARGN})
endfunction()

function(build_tool TOOL_NAME)
    set(CMAKE_AUTOMOC ON)
    set(CMAKE_AUTOUIC ON)
    set(CMAKE_AUTORCC ON)
    set(${TOOL_NAME}_DIR ${CMAKE_CURRENT_SOURCE_DIR})
    file(GLOB_RECURSE ${TOOL_NAME}_header "${${TOOL_NAME}_DIR}/*.h" "${${TOOL_NAME}_DIR}/*.hpp")
    file(GLOB_RECURSE ${TOOL_NAME}_src "${${TOOL_NAME}_DIR}/*.c" "${${TOOL_NAME}_DIR}/*.cpp")
    file(GLOB TOOL_UIS "${${TOOL_NAME}_DIR}/*.ui")
    file(GLOB ${TOOL_NAME}_qrc "${${TOOL_NAME}_DIR}/*.qrc")
    qt5_wrap_ui(ui_FILES ${TOOL_UIS})
    qt5_add_resources(qrc_FILES ${${TOOL_NAME}_qrc})
    message(STATUS ${${TOOL_NAME}_qrc})
    add_executable(${TOOL_NAME} WIN32 ${${TOOL_NAME}_src} ${${TOOL_NAME}_header} ${ui_FILES} ${qrc_FILES})
    target_include_directories(${TOOL_NAME} PRIVATE ${CMAKE_CURRENT_BINARY_DIR}) # 生成的ui_*.h文件在这里
    target_link_libraries(${TOOL_NAME} PRIVATE ${QT5_LIBS} ${ARGN})
endfunction()

function(build_ut UT_NAME)
    set(${UT_NAME}_DIR ${CMAKE_CURRENT_SOURCE_DIR})
    file(GLOB_RECURSE ${UT_NAME}_header "${${UT_NAME}_DIR}/*.h" "${${UT_NAME}_DIR}/*.hpp")
    file(GLOB_RECURSE ${UT_NAME}_src "${${UT_NAME}_DIR}/*.c" "${${UT_NAME}_DIR}/*.cpp")
    add_executable(${UT_NAME} ${${UT_NAME}_src} ${${UT_NAME}_header})
    target_link_libraries(${UT_NAME} PRIVATE ${SYSTEM_LIBS} ${ARGN})
endfunction()

